services:
  mysql-container:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "8000:3306"
    volumes:
      - /host_mnt/Users/bjrajaanumala/Documents/Mission_Impossible/Microservices/Products/Products.API/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    hostname: mysql-host-productsmicroservice

  products-microservice:
    image: rajaanumala/ecommerceproductsmicroservice:v1.0
    environment:
       - MYSQL_HOST:mysql-host-productsmicroservice
       - MYSQL_PASSWORD:admin  
    ports:
      - "5236:5236"
    networks:
      - ecommerce-network 
  
  postgres-container:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=eCommerceUsers
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
  users-microservice:
    image: rajaanumala/usersmicroservice:v1.0
    environment:
      - POSTGRES_HOST=postgres-container
      - POSTGRES_PASSWORD=admin
    ports:
      - "7000:9090"
    networks:
      - ecommerce-network
networks:
 ecommerce-network:
  driver: bridge